create extension if not exists vector;
create type public.app_role as enum ('student','lecturer','department','administrator');
create type public.ticket_status as enum ('open','in_progress','resolved','closed');
create table public.profiles (id uuid primary key references auth.users on delete cascade, full_name text, avatar_url text, preferred_language text default 'en' check (preferred_language in ('en','sw')), created_at timestamptz default now());
create table public.user_roles (user_id uuid references public.profiles on delete cascade, role app_role not null default 'student', primary key(user_id,role));
create table public.departments (id uuid primary key default gen_random_uuid(), name text not null unique, email text, created_at timestamptz default now());
create table public.documents (id uuid primary key default gen_random_uuid(), title text not null, category text not null, storage_path text not null, file_type text not null, status text default 'active' check(status in ('active','archived')), metadata jsonb default '{}', uploaded_by uuid references public.profiles, created_at timestamptz default now(), updated_at timestamptz default now());
create table public.document_chunks (id uuid primary key default gen_random_uuid(), document_id uuid references public.documents on delete cascade, content text not null, page_number int, chunk_index int not null, created_at timestamptz default now());
create table public.embeddings (id uuid primary key default gen_random_uuid(), chunk_id uuid unique references public.document_chunks on delete cascade, embedding vector(768) not null);
create index embeddings_vector_idx on public.embeddings using ivfflat (embedding vector_cosine_ops) with (lists=100);
create table public.conversations (id uuid primary key default gen_random_uuid(), user_id uuid references public.profiles on delete cascade, title text, created_at timestamptz default now());
create table public.messages (id uuid primary key default gen_random_uuid(), conversation_id uuid references public.conversations on delete cascade, role text check(role in ('user','assistant','system')), content text not null, sources jsonb default '[]', confidence numeric, created_at timestamptz default now());
create table public.reminders (id uuid primary key default gen_random_uuid(), user_id uuid references public.profiles on delete cascade, title text not null, due_at timestamptz not null, kind text, completed boolean default false, created_at timestamptz default now());
create table public.notices (id uuid primary key default gen_random_uuid(), title text not null, body text not null, summary text, category text, important_dates jsonb default '[]', author_id uuid references public.profiles, published_at timestamptz default now());
create table public.tickets (id uuid primary key default gen_random_uuid(), created_by uuid references public.profiles, department_id uuid references public.departments, assigned_to uuid references public.profiles, subject text not null, description text not null, status ticket_status default 'open', created_at timestamptz default now(), updated_at timestamptz default now());
create table public.ticket_messages (id uuid primary key default gen_random_uuid(), ticket_id uuid references public.tickets on delete cascade, author_id uuid references public.profiles, body text not null, created_at timestamptz default now());
create or replace function public.is_admin() returns boolean language sql stable security definer as $$select exists(select 1 from public.user_roles where user_id=auth.uid() and role='administrator')$$;
create or replace function public.has_role(required_role public.app_role) returns boolean language sql stable security definer as $$select exists(select 1 from public.user_roles where user_id=auth.uid() and role=required_role)$$;
alter table public.profiles enable row level security; alter table public.documents enable row level security; alter table public.document_chunks enable row level security; alter table public.embeddings enable row level security; alter table public.conversations enable row level security; alter table public.messages enable row level security; alter table public.reminders enable row level security; alter table public.notices enable row level security; alter table public.tickets enable row level security; alter table public.ticket_messages enable row level security;
create policy "profiles own" on public.profiles for all using(id=auth.uid()) with check(id=auth.uid());
create policy "documents authenticated read" on public.documents for select to authenticated using(status='active' or public.is_admin());
create policy "documents admin write" on public.documents for all to authenticated using(public.is_admin()) with check(public.is_admin());
create policy "own conversations" on public.conversations for all to authenticated using(user_id=auth.uid()) with check(user_id=auth.uid());
create policy "own reminders" on public.reminders for all to authenticated using(user_id=auth.uid()) with check(user_id=auth.uid());
create policy "notices read" on public.notices for select to authenticated using(true);
create policy "tickets participants" on public.tickets for select to authenticated using(created_by=auth.uid() or assigned_to=auth.uid() or public.is_admin());
create policy "ticket create" on public.tickets for insert to authenticated with check(created_by=auth.uid());
create policy "messages own conversation" on public.messages for select to authenticated using(exists(select 1 from public.conversations c where c.id=conversation_id and c.user_id=auth.uid()));
create policy "ticket messages participants" on public.ticket_messages for select to authenticated using(exists(select 1 from public.tickets t where t.id=ticket_id and (t.created_by=auth.uid() or t.assigned_to=auth.uid() or public.is_admin())));
create policy "ticket messages create" on public.ticket_messages for insert to authenticated with check(author_id=auth.uid());
create policy "ticket participants update" on public.tickets for update to authenticated using(assigned_to=auth.uid() or public.is_admin());
create policy "admins manage notices" on public.notices for all to authenticated using(public.is_admin()) with check(public.is_admin());
create policy "chunk read with document" on public.document_chunks for select to authenticated using(exists(select 1 from public.documents d where d.id=document_id and (d.status='active' or public.is_admin())));
create policy "embeddings admin only" on public.embeddings for select to authenticated using(public.is_admin());
insert into storage.buckets (id, name, public) values ('documents', 'documents', false) on conflict (id) do nothing;
create policy "admins upload documents" on storage.objects for insert to authenticated with check(bucket_id='documents' and public.is_admin());
create policy "authenticated read documents" on storage.objects for select to authenticated using(bucket_id='documents');
create or replace function public.match_document_chunks(query_embedding vector(768), match_count int default 6) returns table(chunk_id uuid, content text, document_id uuid, title text, page_number int, similarity float) language sql stable as $$select dc.id,dc.content,d.id,d.title,dc.page_number,1-(e.embedding <=> query_embedding) from public.embeddings e join public.document_chunks dc on dc.id=e.chunk_id join public.documents d on d.id=dc.document_id where d.status='active' order by e.embedding <=> query_embedding limit match_count$$;
